/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.agents.pokeclaw.cloud.model
import com.google.gson.annotations.SerializedName



/**
 * 
 *
 * @param code 状态码（200=成功）
 * @param msg 提示消息
 * @param `data` 响应数据
 */
data class CommonResult (

    /* 状态码（200=成功） */
    @SerializedName("code")
    val code: kotlin.Int? = null,

    /* 提示消息 */
    @SerializedName("msg")
    val msg: kotlin.String? = null,

    /* 响应数据 */
    @SerializedName("data")
    val `data`: kotlin.Any? = null

) {


}

