/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param batteryLevel 电量百分比 (0-100)
 * @param isCharging 是否正在充电
 * @param networkType 网络类型
 */
@Parcelize


data class DeviceHeartbeatRequest (

    /* 电量百分比 (0-100) */
    @SerializedName("batteryLevel")
    val batteryLevel: kotlin.Int? = null,

    /* 是否正在充电 */
    @SerializedName("isCharging")
    val isCharging: kotlin.Boolean? = null,

    /* 网络类型 */
    @SerializedName("networkType")
    val networkType: DeviceHeartbeatRequest.NetworkType? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
     * 网络类型
     *
     * Values: wifi,cellular,offline
     */
    enum class NetworkType(val value: kotlin.String) {
        @SerializedName(value = "wifi") wifi("wifi"),
        @SerializedName(value = "cellular") cellular("cellular"),
        @SerializedName(value = "offline") offline("offline");
    }

}

