/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.agents.pokeclaw.cloud.model
import com.google.gson.annotations.SerializedName



/**
 * 
 *
 * @param id 
 * @param taskUuid 
 * @param deviceId 
 * @param command 
 * @param mode 
 * @param priority 
 * @param source 
 * @param status 
 * @param result 
 * @param errorMessage 
 * @param executionTimeMs 
 * @param toolCalls 
 * @param evidenceUrls 
 * @param modelUsed 
 * @param assignedAt 
 * @param completedAt 
 * @param retryCount 
 * @param createTime 
 */
data class DeviceTaskVO (

    @SerializedName("id")
    val id: kotlin.Int? = null,

    @SerializedName("taskUuid")
    val taskUuid: kotlin.String? = null,

    @SerializedName("deviceId")
    val deviceId: kotlin.String? = null,

    @SerializedName("command")
    val command: kotlin.String? = null,

    @SerializedName("mode")
    val mode: kotlin.String? = null,

    @SerializedName("priority")
    val priority: kotlin.String? = null,

    @SerializedName("source")
    val source: kotlin.String? = null,

    @SerializedName("status")
    val status: DeviceTaskVO.Status? = null,

    @SerializedName("result")
    val result: kotlin.String? = null,

    @SerializedName("errorMessage")
    val errorMessage: kotlin.String? = null,

    @SerializedName("executionTimeMs")
    val executionTimeMs: kotlin.Int? = null,

    @SerializedName("toolCalls")
    val toolCalls: kotlin.String? = null,

    @SerializedName("evidenceUrls")
    val evidenceUrls: kotlin.String? = null,

    @SerializedName("modelUsed")
    val modelUsed: kotlin.String? = null,

    @SerializedName("assignedAt")
    val assignedAt: java.time.OffsetDateTime? = null,

    @SerializedName("completedAt")
    val completedAt: java.time.OffsetDateTime? = null,

    @SerializedName("retryCount")
    val retryCount: kotlin.Int? = null,

    @SerializedName("createTime")
    val createTime: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: PENDING,RUNNING,SUCCESS,FAILED,CANCELLED
     */
    enum class Status(val value: kotlin.String) {
        @SerializedName("PENDING") PENDING("PENDING"),
        @SerializedName("RUNNING") RUNNING("RUNNING"),
        @SerializedName("SUCCESS") SUCCESS("SUCCESS"),
        @SerializedName("FAILED") FAILED("FAILED"),
        @SerializedName("CANCELLED") CANCELLED("CANCELLED");
    }

}

