/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.agents.pokeclaw.cloud.model
import com.google.gson.annotations.SerializedName



/**
 * 
 *
 * @param status 新状态: 0=离线 1=在线 2=禁用
 */
data class DeviceUpdateStatusRequest (

    /* 新状态: 0=离线 1=在线 2=禁用 */
    @SerializedName("status")
    val status: kotlin.Int

) {


}

