/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model

import io.agents.pokeclaw.cloud.model.DeviceRegisterResponse

import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param code 
 * @param `data` 
 */
@Parcelize


data class DeviceRegister200Response (

    @SerializedName("code")
    val code: kotlin.Int? = null,

    @SerializedName("data")
    val `data`: DeviceRegisterResponse? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

