/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.agents.pokeclaw.cloud.model
    import com.google.gson.annotations.SerializedName



/**
 * 
 *
 * @param command 要执行的命令
 * @param mode 执行模式
 */
data class DeviceExecuteRequest (

    /* 要执行的命令 */
    @SerializedName("command")
    val command: kotlin.String,

    /* 执行模式 */
    @SerializedName("mode")
    val mode: DeviceExecuteRequest.Mode? = Mode.TASK

) {

    /**
     * 执行模式
     *
     * Values: TASK,INTERACTIVE
     */
    enum class Mode(val value: kotlin.String) {
        @SerializedName("TASK") TASK("TASK"),
        @SerializedName("INTERACTIVE") INTERACTIVE("INTERACTIVE");
    }

}

