/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.agents.pokeclaw.cloud.model
import com.google.gson.annotations.SerializedName



/**
 * 
 *
 * @param deviceId 设备 ID（模糊搜索）
 * @param deviceName 设备名称（模糊搜索）
 * @param status 状态筛选: 0=离线 1=在线 2=禁用
 * @param pageNo 
 * @param pageSize 
 */
data class DevicePageRequest (

    /* 设备 ID（模糊搜索） */
    @SerializedName("deviceId")
    val deviceId: kotlin.String? = null,

    /* 设备名称（模糊搜索） */
    @SerializedName("deviceName")
    val deviceName: kotlin.String? = null,

    /* 状态筛选: 0=离线 1=在线 2=禁用 */
    @SerializedName("status")
    val status: kotlin.Int? = null,

    @SerializedName("pageNo")
    val pageNo: kotlin.Int? = 1,

    @SerializedName("pageSize")
    val pageSize: kotlin.Int? = 10

) {


}

