/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param pendingTaskCount 待处理任务数量
 * @param skillVersion 当前技能版本号
 * @param serverTime 服务器时间戳（毫秒）
 */
@Parcelize


data class DeviceHeartbeatResponse (

    /* 待处理任务数量 */
    @SerializedName("pendingTaskCount")
    val pendingTaskCount: kotlin.Int? = null,

    /* 当前技能版本号 */
    @SerializedName("skillVersion")
    val skillVersion: kotlin.Int? = null,

    /* 服务器时间戳（毫秒） */
    @SerializedName("serverTime")
    val serverTime: kotlin.Int? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

