/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param command 要执行的命令
 * @param mode 执行模式
 */
@Parcelize


data class DeviceExecuteRequest (

    /* 要执行的命令 */
    @SerializedName("command")
    val command: kotlin.String,

    /* 执行模式 */
    @SerializedName("mode")
    val mode: DeviceExecuteRequest.Mode? = Mode.TASK

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
     * 执行模式
     *
     * Values: TASK,INTERACTIVE
     */
    enum class Mode(val value: kotlin.String) {
        @SerializedName(value = "TASK") TASK("TASK"),
        @SerializedName(value = "INTERACTIVE") INTERACTIVE("INTERACTIVE");
    }

}

