/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param status 新状态: 0=离线 1=在线 2=禁用
 */
@Parcelize


data class DeviceUpdateStatusRequest (

    /* 新状态: 0=离线 1=在线 2=禁用 */
    @SerializedName("status")
    val status: kotlin.Int

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

