/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param status 状态筛选: PENDING/RUNNING/SUCCESS/FAILED/CANCELLED
 * @param taskUuid 任务 UUID（模糊搜索）
 * @param pageNo 
 * @param pageSize 
 */
@Parcelize


data class DeviceTaskPageRequest (

    /* 状态筛选: PENDING/RUNNING/SUCCESS/FAILED/CANCELLED */
    @SerializedName("status")
    val status: kotlin.String? = null,

    /* 任务 UUID（模糊搜索） */
    @SerializedName("taskUuid")
    val taskUuid: kotlin.String? = null,

    @SerializedName("pageNo")
    val pageNo: kotlin.Int? = 1,

    @SerializedName("pageSize")
    val pageSize: kotlin.Int? = 10

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

