/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param deviceId 设备唯一标识（客户端生成，如 IMEI/SN）
 * @param deviceName 设备名称（用户自定义）
 * @param deviceModel 设备型号
 * @param androidVersion Android 版本
 * @param appVersion PokeClaw App 版本
 * @param publicKey 设备公钥（用于后续 JWT 签名验证）
 */
@Parcelize


data class DeviceRegisterRequest (

    /* 设备唯一标识（客户端生成，如 IMEI/SN） */
    @SerializedName("deviceId")
    val deviceId: kotlin.String,

    /* 设备名称（用户自定义） */
    @SerializedName("deviceName")
    val deviceName: kotlin.String? = null,

    /* 设备型号 */
    @SerializedName("deviceModel")
    val deviceModel: kotlin.String? = null,

    /* Android 版本 */
    @SerializedName("androidVersion")
    val androidVersion: kotlin.String? = null,

    /* PokeClaw App 版本 */
    @SerializedName("appVersion")
    val appVersion: kotlin.String? = null,

    /* 设备公钥（用于后续 JWT 签名验证） */
    @SerializedName("publicKey")
    val publicKey: kotlin.String? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

