/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param id 主键 ID
 * @param deviceId 设备唯一标识
 * @param deviceName 设备名称
 * @param deviceModel 设备型号
 * @param androidVersion Android 版本
 * @param appVersion 应用版本
 * @param status 设备状态: 0=离线 1=在线 2=禁用
 * @param batteryLevel 电量
 * @param isCharging 是否充电中
 * @param networkType 网络类型
 * @param lastHeartbeatAt 最后心跳时间
 * @param currentTaskId 当前执行的任务 ID
 * @param skillVersion 技能版本号
 * @param createTime 创建时间
 */
@Parcelize


data class DeviceVO (

    /* 主键 ID */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* 设备唯一标识 */
    @SerializedName("deviceId")
    val deviceId: kotlin.String? = null,

    /* 设备名称 */
    @SerializedName("deviceName")
    val deviceName: kotlin.String? = null,

    /* 设备型号 */
    @SerializedName("deviceModel")
    val deviceModel: kotlin.String? = null,

    /* Android 版本 */
    @SerializedName("androidVersion")
    val androidVersion: kotlin.String? = null,

    /* 应用版本 */
    @SerializedName("appVersion")
    val appVersion: kotlin.String? = null,

    /* 设备状态: 0=离线 1=在线 2=禁用 */
    @SerializedName("status")
    val status: kotlin.Int? = null,

    /* 电量 */
    @SerializedName("batteryLevel")
    val batteryLevel: kotlin.Int? = null,

    /* 是否充电中 */
    @SerializedName("isCharging")
    val isCharging: kotlin.Boolean? = null,

    /* 网络类型 */
    @SerializedName("networkType")
    val networkType: kotlin.String? = null,

    /* 最后心跳时间 */
    @SerializedName("lastHeartbeatAt")
    val lastHeartbeatAt: java.time.OffsetDateTime? = null,

    /* 当前执行的任务 ID */
    @SerializedName("currentTaskId")
    val currentTaskId: kotlin.String? = null,

    /* 技能版本号 */
    @SerializedName("skillVersion")
    val skillVersion: kotlin.Int? = null,

    /* 创建时间 */
    @SerializedName("createTime")
    val createTime: java.time.OffsetDateTime? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

