/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param list 
 * @param total 总记录数
 */
@Parcelize


data class PageResult (

    @SerializedName("list")
    val list: kotlin.collections.List<kotlin.Any>? = null,

    /* 总记录数 */
    @SerializedName("total")
    val total: kotlin.Int? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

