/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param taskUuid 任务 UUID
 * @param command 执行命令
 * @param mode 执行模式
 * @param createdAt 创建时间戳（毫秒）
 * @param priority 优先级
 */
@Parcelize


data class PendingTaskItem (

    /* 任务 UUID */
    @SerializedName("taskUuid")
    val taskUuid: kotlin.String? = null,

    /* 执行命令 */
    @SerializedName("command")
    val command: kotlin.String? = null,

    /* 执行模式 */
    @SerializedName("mode")
    val mode: kotlin.String? = null,

    /* 创建时间戳（毫秒） */
    @SerializedName("createdAt")
    val createdAt: kotlin.Int? = null,

    /* 优先级 */
    @SerializedName("priority")
    val priority: kotlin.String? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

