/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.agents.pokeclaw.cloud.model

import io.agents.pokeclaw.cloud.model.SubmitTaskResult200ResponseData
import com.google.gson.annotations.SerializedName


/**
 * 
 *
 * @param code 
 * @param `data` 
 */
data class SubmitTaskResult200Response (

    @SerializedName("code")
    val code: kotlin.Int? = null,

    @SerializedName("data")
    val `data`: SubmitTaskResult200ResponseData? = null

) {


}

