/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param status 任务状态
 * @param result 执行结果文本
 * @param errorMessage 错误信息（status=FAILED 时必填）
 * @param executionTimeMs 执行耗时（毫秒）
 * @param toolCalls 工具调用记录（JSON 字符串）
 * @param evidenceUrls 证据 URL 列表（JSON 字符串）
 * @param modelUsed 使用的模型
 */
@Parcelize


data class TaskResultRequest (

    /* 任务状态 */
    @SerializedName("status")
    val status: TaskResultRequest.Status,

    /* 执行结果文本 */
    @SerializedName("result")
    val result: kotlin.String? = null,

    /* 错误信息（status=FAILED 时必填） */
    @SerializedName("errorMessage")
    val errorMessage: kotlin.String? = null,

    /* 执行耗时（毫秒） */
    @SerializedName("executionTimeMs")
    val executionTimeMs: kotlin.Int? = null,

    /* 工具调用记录（JSON 字符串） */
    @SerializedName("toolCalls")
    val toolCalls: kotlin.String? = null,

    /* 证据 URL 列表（JSON 字符串） */
    @SerializedName("evidenceUrls")
    val evidenceUrls: kotlin.String? = null,

    /* 使用的模型 */
    @SerializedName("modelUsed")
    val modelUsed: kotlin.String? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
     * 任务状态
     *
     * Values: SUCCESS,FAILED,RUNNING,CANCELLED
     */
    enum class Status(val value: kotlin.String) {
        @SerializedName(value = "SUCCESS") SUCCESS("SUCCESS"),
        @SerializedName(value = "FAILED") FAILED("FAILED"),
        @SerializedName(value = "RUNNING") RUNNING("RUNNING"),
        @SerializedName(value = "CANCELLED") CANCELLED("CANCELLED");
    }

}

