/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param deviceToken 新的 JWT 设备令牌
 * @param expiresIn 过期时间（秒）
 */
@Parcelize


data class TokenRefreshResponse (

    /* 新的 JWT 设备令牌 */
    @SerializedName("deviceToken")
    val deviceToken: kotlin.String? = null,

    /* 过期时间（秒） */
    @SerializedName("expiresIn")
    val expiresIn: kotlin.Int? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

