/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.agents.pokeclaw.cloud.model


import com.google.gson.annotations.SerializedName
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.io.Serializable

/**
 * 
 *
 * @param refreshToken 刷新令牌
 */
@Parcelize


data class TokenRefreshRequest (

    /* 刷新令牌 */
    @SerializedName("refreshToken")
    val refreshToken: kotlin.String

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

