"""Append 11 ralph-r2 stories to .omc/prd.json."""
import json
from pathlib import Path

PRD_PATH = Path('.omc/prd.json')

with PRD_PATH.open('r', encoding='utf-8') as f:
    prd = json.load(f)

new_stories = [
    {
        "id": "US-B-CMP-1-1-LOBSTER-ROLE",
        "title": "小虾角色模型（端侧持久化 + 云端可调）",
        "description": "As a PokeClaw user, I want different AI personalities (roles) so that I can switch the agent's behavior for different contexts",
        "category": "divergent",
        "source": "US-CLAW-CMP-1-1 (dyq) + 头脑风暴",
        "priority": "P1",
        "passes": False,
        "scope": "single-end + light-cloud",
        "dependsOn": [],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/role/LobsterRole.kt",
            "app/src/main/java/io/agents/pokeclaw/role/LobsterRoleManager.kt",
            "app/src/main/java/io/agents/pokeclaw/role/LobsterRoleSync.kt",
            "app/src/main/java/io/agents/pokeclaw/ui/role/LobsterRoleManagerActivity.kt",
            "app/src/main/res/layout/activity_lobster_role_manager.xml",
        ],
        "acceptanceCriteria": [
            "LobsterRole 数据类: id, name, role, status (ENABLED|PAUSED|DISABLED), duties (List<String>), history, version, updatedAt, source (USER|SYSTEM)",
            "LobsterRoleManager.kt: list() / get(id) / activate(id) / pause(id) / disable(id) / createLocal() / updateLocal()",
            "端侧 KV 持久化 (MMKV key: lobster_roles_v1)",
            "默认角色: 通用助手 / 工作模式 / 家庭模式 / 谨慎模式",
            "角色状态机可手动切换",
            "当前激活角色 ID 写到 KVUtils.LOBSTER_ACTIVE_ROLE_ID",
            "TaskOrchestrator.startNewTask 注入角色到 system prompt",
            "XLog.d lobster-role activate log line",
        ],
        "learnings": [],
    },
    {
        "id": "US-B-OW-001-ON-DEVICE-CONSOLE",
        "title": "端侧后台控制台（端内远控通道）",
        "description": "As a tester, I want an in-app control console so I can drive PokeClaw tasks without the cloud admin",
        "category": "divergent",
        "source": "US-CLAW-OW-001 (dyq) + 头脑风暴",
        "priority": "P2",
        "passes": False,
        "scope": "single-end",
        "dependsOn": [],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/ui/console/OnDeviceConsoleActivity.kt",
            "app/src/main/res/layout/activity_on_device_console.xml",
        ],
        "acceptanceCriteria": [
            "OnDeviceConsoleActivity.kt - 端内 Activity",
            "顶部 EditText 输入指令 + 发送按钮 + 历史指令下拉",
            "点击发送走 TaskOrchestrator.startNewTask(channel=LOCAL, task, messageId=UUID)",
            "中部 RecyclerView 实时显示任务事件 via TaskEventCallback",
            "底部显示当前 active model + role + network type",
            "不依赖云端 (channel=Channel.LOCAL)",
            "注册到 AndroidManifest.xml",
            "XLog.d on-device-console send task log line",
        ],
        "learnings": [],
    },
    {
        "id": "US-B-CMP-1-3-TASK-TRACKER",
        "title": "任务追踪补完（状态机扩展 + 端侧持久化）",
        "description": "As a developer, I want a complete task status state machine persisted locally so I can audit/debug",
        "category": "divergent",
        "source": "US-CLAW-CMP-1-3 (dyq) + 头脑风暴",
        "priority": "P1",
        "passes": False,
        "scope": "single-end",
        "dependsOn": [],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/task/TaskTracker.kt",
            "app/src/main/java/io/agents/pokeclaw/TaskOrchestrator.kt (modify)",
            "app/src/main/java/io/agents/pokeclaw/TaskSessionStore.kt (modify, add REJECTED)",
        ],
        "acceptanceCriteria": [
            "TaskTracker 状态机扩展: PENDING/CLAIMED/RUNNING/PAUSED/COMPLETED/FAILED/ABORTED/REJECTED",
            "task_track SQLite 表: id, taskUuid, actor, status, prevStatus, occurredAt, note",
            "transition(taskUuid, newStatus, actor, note) 方法: 写入并 XLog.i",
            "query(taskUuid) / query(actor, sinceMillis) / query(status, limit) 三个查询入口",
            "在 TaskOrchestrator 关键节点埋点: onAcquire CLAIMED, onLoopStart RUNNING, onComplete COMPLETED, onError FAILED, revokeCurrentTask ABORTED",
            "容量: 保留最近 200 条, 超出 FIFO 丢弃",
            "XLog.i task-track transition log line",
        ],
        "learnings": [],
    },
    {
        "id": "US-B-CMP-2-3-CLOUD-DISPATCH",
        "title": "接收云端指令（轮询 + 投递本地执行）",
        "description": "As a device registered to dyq cloud, I want to consume pending tasks and dispatch to local TaskOrchestrator",
        "category": "divergent",
        "source": "US-CLAW-CMP-2-3 (dyq) + 头脑风暴",
        "priority": "P1",
        "passes": False,
        "scope": "single-end",
        "dependsOn": ["US-B-CMP-1-3-TASK-TRACKER"],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/cloud/CloudNodeOrchestrator.kt (modify)",
        ],
        "acceptanceCriteria": [
            "CloudNodeOrchestrator.dispatchPendingTasks() - 在心跳响应中检测 pendingTaskCount > 0 时调用",
            "调 GET /api/claw-device/devices/{deviceId}/pending-tasks (沿用现有 Retrofit API)",
            "对每个 PendingTaskItem: 立即上报 ACK, 写入 TaskTracker.transition(taskUuid, CLAIMED, cloud), 走 TaskOrchestrator.startNewTask",
            "失败任务走现有 CloudTaskExecutor.executeControlAction 路径",
            "WebSocket 路径保留 CloudWebSocketClient 钩子, 本期默认走轮询",
            "XLog.d cloud-dispatch count taskUuid command log line",
        ],
        "learnings": [],
    },
    {
        "id": "US-B-3T-002-ENROLL-MULTI",
        "title": "设备注册兼容性（多后端切换）",
        "description": "As a tester on different environments, I want to switch between local/staging/production backends",
        "category": "divergent",
        "source": "US-CLAW3T-002 (dyq) + 头脑风暴",
        "priority": "P2",
        "passes": False,
        "scope": "single-end",
        "dependsOn": [],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/cloud/ClawNodeEnrollmentManager.kt (modify)",
            "app/src/main/java/io/agents/pokeclaw/utils/KVUtils.kt (modify, add CLAW_ENROLL_* keys)",
        ],
        "acceptanceCriteria": [
            "ClawNodeEnrollmentManager 支持多后端枚举: LOCAL/STAGING/PRODUCTION",
            "每个后端独立存: deviceId + deviceToken + refreshToken (MMKV key: claw_enroll_{env}_*)",
            "Settings 云端控制 新增后端选择 RadioGroup (默认 PRODUCTION)",
            "注册失败显示 4xx/5xx 错误码 + 具体原因 + 重试按钮",
            "切换后端不丢失其他后端的 token (仅切换 active 指针)",
            "XLog.i enroll env status code log line",
        ],
        "learnings": [],
    },
    {
        "id": "US-B-MISSED-CALL-FOLLOWUP",
        "title": "错过电话自动跟进 (SMS)",
        "description": "As a user who misses a call, I want PokeClaw to send a follow-up SMS",
        "category": "divergent",
        "source": "BACKLOG P0 missed-call-auto-follow-up + 头脑风暴",
        "priority": "P1",
        "passes": False,
        "scope": "single-end",
        "dependsOn": [],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/receiver/MissedCallReceiver.kt",
            "app/src/main/java/io/agents/pokeclaw/job/MissedCallFollowupJob.kt",
            "app/src/main/AndroidManifest.xml (modify)",
        ],
        "acceptanceCriteria": [
            "MissedCallReceiver 注册 android.intent.action.PHONE_STATE 广播",
            "判定逻辑: EXTRA_STATE=IDLE + incomingNumber 非空 + 通话时长 < 5s",
            "MissedCallFollowupJob (WorkManager 5s 延迟): SmsManager.sendTextMessage 发预置短信",
            "短信模板可在 Settings 改",
            "ComposeChatActivity 顶部显示自动跟进卡片",
            "关键约束: 不依赖 accessibility / WhatsApp 自动化",
            "关闭开关: Settings 错过电话自动跟进",
            "必要权限: READ_PHONE_STATE / SEND_SMS",
            "XLog.i missed-call log line",
        ],
        "learnings": [],
    },
    {
        "id": "US-B-LOCAL-INSTRUCTIONS",
        "title": "持久化全局指令",
        "description": "As a user, I want a persistent global instructions text so every new task includes my personal context",
        "category": "divergent",
        "source": "BACKLOG P1 persistent-global-instructions + 头脑风暴",
        "priority": "P1",
        "passes": False,
        "scope": "single-end",
        "dependsOn": [],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/utils/KVUtils.kt (modify)",
            "app/src/main/java/io/agents/pokeclaw/TaskOrchestrator.kt (modify)",
            "app/src/main/java/io/agents/pokeclaw/ui/settings/SettingsActivity.kt (modify)",
        ],
        "acceptanceCriteria": [
            "Settings 新增全局指令多行 EditText (≤500 字符校验)",
            "存储: KVUtils.LOBSTER_GLOBAL_INSTRUCTIONS",
            "AgentConfig.systemPrompt 注入位置",
            "不覆盖硬安全规则和工具规则, 单独段落",
            "切换聊天/任务时全局指令不丢失",
            "删除时仅清空字符串, 不删除 KV key",
            "XLog.d local-instructions len log line",
        ],
        "learnings": [],
    },
    {
        "id": "US-B-1B-MODELS",
        "title": "1B / 1.5B 轻量模型",
        "description": "As a low-RAM device user, I want smaller model options so I can still use PokeClaw",
        "category": "divergent",
        "source": "BACKLOG P1 more-small-local-model-options + 头脑风暴",
        "priority": "P1",
        "passes": False,
        "scope": "single-end",
        "dependsOn": [],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/agent/llm/LocalModelManager.kt (modify)",
        ],
        "acceptanceCriteria": [
            "LocalModelManager.AVAILABLE_MODELS 新增 gemma4-1b (0.6GB, minRamGb=4)",
            "新增 gemma4-1.5b (1.0GB, minRamGb=6)",
            "URL 沿用 litert-community 命名规则 (占位 URL 需用户填)",
            "recommendedModel() 改为 3 段判定: <6GB→1B, 6-8GB→1.5B, >8GB→2.6GB",
            "LlmConfigActivity 列表自动显示新条目",
            "不改 LiteRT-LM runtime 路径",
            "XLog.d model-recommend log line",
        ],
        "learnings": [],
    },
    {
        "id": "US-B-ROLE-STORE",
        "title": "角色商店（轻云契约 + 端侧 cache）",
        "description": "As a user, I want to browse and activate pre-defined roles from a (mock) cloud role store",
        "category": "divergent",
        "source": "头脑风暴 (角色商店 组合轻云)",
        "priority": "P2",
        "passes": False,
        "scope": "single-end + light-cloud",
        "dependsOn": ["US-B-CMP-1-1-LOBSTER-ROLE"],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/role/LobsterRoleStore.kt",
            "app/src/main/java/io/agents/pokeclaw/ui/role/LobsterRoleStoreActivity.kt",
            "app/src/main/res/layout/activity_lobster_role_store.xml",
            "app/src/main/java/io/agents/pokeclaw/cloud/api/DeviceApi.kt (modify, add roles endpoint)",
        ],
        "acceptanceCriteria": [
            "LobsterRoleStore.kt: list / get / activate / sync",
            "端侧 cache 命中即返回; 首次或缓存过期触发 sync()",
            "sync() 调 GET /api/claw/roles/list (契约定义, 本期不联调跑通)",
            "响应写入 lobster_roles_store 表",
            "Settings 角色商店 入口: 列表 + 激活按钮 + 状态显示",
            "端侧只读 + activate; 写操作在云端管理后台",
            "离线时显示本地 cache 列表 + 云端不同步角标",
            "XLog.d role-store sync log line",
        ],
        "learnings": [],
    },
    {
        "id": "US-B-EXPERIENCE-READ",
        "title": "经验包端侧读取（轻云契约 + few-shot 注入）",
        "description": "As a user, I want to reuse my own past successful/failed experiences as few-shot prompts",
        "category": "divergent",
        "source": "头脑风暴 (经验回读 组合轻云)",
        "priority": "P2",
        "passes": False,
        "scope": "single-end + light-cloud",
        "dependsOn": ["US-3T-006-EXPERIENCE-UPLOAD"],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/cloud/ExperienceReader.kt",
            "app/src/main/java/io/agents/pokeclaw/cloud/ExperienceLocalCache.kt",
            "app/src/main/java/io/agents/pokeclaw/cloud/api/DeviceApi.kt (modify, add experience list)",
        ],
        "acceptanceCriteria": [
            "ExperienceReader 与 ExperienceUploader 对称",
            "契约 GET /api/claw-experience/list?deviceId=X&since=Y",
            "使用场景: 相似任务开始时, 注入 top-3 成功 + top-1 失败经验作为 few-shot",
            "离线时 fallback 到 ExperienceLocalCache (KV 持久化上次拉到的副本)",
            "仍遵守只读自己写的语义, 不读他人经验",
            "XLog.d experience-read log line",
        ],
        "learnings": [],
    },
    {
        "id": "US-B-TASK-APPROVAL",
        "title": "主人审批（端内弹窗 + 上报云端）",
        "description": "As a user, I want to approve/reject high-stakes tasks before they execute",
        "category": "divergent",
        "source": "头脑风暴 (主人审批 组合轻云)",
        "priority": "P1",
        "passes": False,
        "scope": "single-end + light-cloud",
        "dependsOn": ["US-B-CMP-1-3-TASK-TRACKER"],
        "estimatedFiles": [
            "app/src/main/java/io/agents/pokeclaw/ui/chat/OwnerApprovalDialog.kt",
            "app/src/main/java/io/agents/pokeclaw/TaskOrchestrator.kt (modify)",
            "app/src/main/java/io/agents/pokeclaw/cloud/api/DeviceApi.kt (modify, add task-approval)",
        ],
        "acceptanceCriteria": [
            "TaskOrchestrator.startNewTask 增加 requiresApproval Boolean 参数",
            "触发条件: 任务 metadata 含 priority=HIGH 或 costYuan >= 1.0",
            "弹窗 OwnerApprovalDialog (端内 AlertDialog, 非云端推送)",
            "主人点批准 继续执行; 拒绝 任务进入 REJECTED 终态 (写 TaskTracker)",
            "审批结果通过 POST /api/claw/task-approval (契约 + 端侧上报) 写入云端",
            "离线时审批结果入 CloudEventQueue, 网络恢复后补报",
            "弹窗内显示任务摘要 + 预计成本 + 风险评估",
            "XLog.i task-approval log line",
        ],
        "learnings": [],
    },
]

prd['userStories'].extend(new_stories)
existing = prd.get('description', '')
prd['description'] = existing + ' | R2: 11 条端侧+轻云增量'

with PRD_PATH.open('w', encoding='utf-8') as f:
    json.dump(prd, f, ensure_ascii=False, indent=2)

print(f'Appended {len(new_stories)} R2 stories. Total now: {len(prd["userStories"])}')
